### ISSUE TITLE
eigen 3.3.7 download lonk is no longer supported !

### ISSUE THREAD

**Issue by MohamadHalwani** [ethz-asl/eigen_catkin#31]
In the  CMakelists.txt file this download link is no longer available "http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2" 
I don't know if this is what causing my problem after running catkin_make.

```
[ 24%] Building CXX object minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/src/export-rotation-quaternion.cc.o
In file included from /home/ubuntu/emvs_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:15:0,
                 from /home/ubuntu/emvs_ws/src/numpy_eigen/src/autogen_module/numpy_eigen_export_module.cpp:2:
/home/ubuntu/emvs_ws/src/numpy_eigen/include/numpy_eigen/boost_python_headers.hpp:23:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
In file included from /home/ubuntu/emvs_ws/src/numpy_eigen/include/numpy_eigen/NumpyEigenConverter.hpp:15:0,
                 from /home/ubuntu/emvs_ws/src/numpy_eigen/src/autogen_module/import_int.cpp:4:
/home/ubuntu/emvs_ws/src/numpy_eigen/include/numpy_eigen/boost_python_headers.hpp:23:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
In file included from /home/ubuntu/emvs_ws/src/minkindr/minkindr_python/src/module.cpp:1:0:
/home/ubuntu/emvs_ws/src/numpy_eigen/include/numpy_eigen/boost_python_headers.hpp:23:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
numpy_eigen/CMakeFiles/numpy_eigen.dir/build.make:75: recipe for target 'numpy_eigen/CMakeFiles/numpy_eigen.dir/src/autogen_module/import_int.cpp.o' failed
make[2]: *** [numpy_eigen/CMakeFiles/numpy_eigen.dir/src/autogen_module/import_int.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
numpy_eigen/CMakeFiles/numpy_eigen.dir/build.make:62: recipe for target 'numpy_eigen/CMakeFiles/numpy_eigen.dir/src/autogen_module/numpy_eigen_export_module.cpp.o' failed
make[2]: *** [numpy_eigen/CMakeFiles/numpy_eigen.dir/src/autogen_module/numpy_eigen_export_module.cpp.o] Error 1
minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/build.make:62: recipe for target 'minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/src/module.cpp.o' failed
make[2]: *** [minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/src/module.cpp.o] Error 1
CMakeFiles/Makefile2:3146: recipe for target 'numpy_eigen/CMakeFiles/numpy_eigen.dir/all' failed
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [numpy_eigen/CMakeFiles/numpy_eigen.dir/all] Error 2
/home/ubuntu/emvs_ws/src/eigen_catkin_tools/eigen_catkin_info/src/eigen_catkin_info.cpp:2:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
eigen_catkin_tools/eigen_catkin_info/CMakeFiles/eigen_catkin_info.dir/build.make:62: recipe for target 'eigen_catkin_tools/eigen_catkin_info/CMakeFiles/eigen_catkin_info.dir/src/eigen_catkin_info.cpp.o' failed
make[2]: *** [eigen_catkin_tools/eigen_catkin_info/CMakeFiles/eigen_catkin_info.dir/src/eigen_catkin_info.cpp.o] Error 1
CMakeFiles/Makefile2:1502: recipe for target 'eigen_catkin_tools/eigen_catkin_info/CMakeFiles/eigen_catkin_info.dir/all' failed
make[1]: *** [eigen_catkin_tools/eigen_catkin_info/CMakeFiles/eigen_catkin_info.dir/all] Error 2
In file included from /home/ubuntu/emvs_ws/src/minkindr/minkindr_python/src/export-rotation-quaternion.cc:1:0:
/home/ubuntu/emvs_ws/src/minkindr/minkindr/include/kindr/minimal/rotation-quaternion.h:30:23: fatal error: Eigen/Dense: No such file or directory
compilation terminated.
minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/build.make:75: recipe for target 'minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/src/export-rotation-quaternion.cc.o' failed
make[2]: *** [minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/src/export-rotation-quaternion.cc.o] Error 1
CMakeFiles/Makefile2:3228: recipe for target 'minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/all' failed
make[1]: *** [minkindr/minkindr_python/CMakeFiles/minkindr_python.dir/all] Error 2
[ 24%] Built target _dvs_msgs_generate_messages_check_deps_EventArray
[ 24%] Built target _dvs_msgs_generate_messages_check_deps_Event
-- Retrying...
-- Using src='http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2'
-- Retry after 5 seconds (attempt #2) ...
^CTraceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_make", line 298, in <module>
    sys.exit(main())
  File "/opt/ros/kinetic/bin/catkin_make", line 242, in main
    run_command(cmd, make_path)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 240, in run_command
    proc.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
eigen_catkin/CMakeFiles/eigen_src.dir/build.make:90: recipe for target 'eigen_catkin/eigen_src-prefix/src/eigen_src-stamp/eigen_src-download' failed
make[2]: *** [eigen_catkin/eigen_src-prefix/src/eigen_src-stamp/eigen_src-download] Interrupt
CMakeFiles/Makefile2:1448: recipe for target 'eigen_catkin/CMakeFiles/eigen_src.dir/all' failed
make[1]: *** [eigen_catkin/CMakeFiles/eigen_src.dir/all] Interrupt
Makefile:140: recipe for target 'all' failed
make: *** [all] Interrupt

```

**Comment by trevphil** [comment]
I'm having the same issue. Created a [PR](https://github.com/ethz-asl/eigen_catkin/pull/32) with the updated URL.

**Comment by MohamadHalwani** [comment]
How come I'm still getting the same errror !? 
```
Errors     << eigen_catkin:make /home/ubuntu/logs/eigen_catkin/build.make.000.log                                  
CMake Error at eigen_src-stamp/download-eigen_src.cmake:159 (message):
  Each download failed!
```

    error: downloading 'http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
         Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,::1'
    Trying 18.205.93.0:80...


Why is it still looking in bitbucket.org ?!
